config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/quantity', to: 'carts#quantity'
  get '/search', to: 'orders#search'
  post 'checkout', to: 'carts#checkout'
  post 'retire', to: 'items#retire'
  resources :carts
  resources :restaurants do
    resources :orders do
      resources :items
    end
  end
  resources :restaurants do
    resources :categories do
      resources :items
    end
  end
  root to: 'restaurants#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :item_orders, dependent: :destroy
  has_many :items, through: :item_orders, dependent: :destroy

  scope :user_orders, ->(user_id, restaurant_id) { where(user_id: user_id, restaurant_id: restaurant_id) }
  scope :restaurant_orders, ->(restaurant_id) { where(restaurant_id: restaurant_id) }
  scope :find_orders_in_item_order, ->(id) { ItemOrder.all.where(order_id: id) }

  validates :status, presence: true
  validates :total, numericality: { only_integer: true, greater_than: 0 }
  enum status: {
    ordered: 0,
    completed: 1,
    cancelled: 2
  }
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# Customer controller action
class OrdersController < ApplicationController
  before_action :find_order, only: %i[show update]
  before_action :create_session, only: %i[index]

  def index
    @orders = if admin?
                Order.restaurant_orders(params[:restaurant_id])
              else
                Order.user_orders(params[:user_id], params[:restaurant_id])
              end
    authorize @orders
    session[:restaurant_id] = params[:restaurant_id]
  end

  def show
    authorize @order
    @itemorders = Order.find_orders_in_item_order(params[:id])
  end

  def update
    authorize @order
    if @order.update(status: params[:status], restaurant_id: @order.restaurant_id, user_id: @order.user_id,
                     total: @order.total)
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = @order.errors.full_messages
      redirect_to(request.referer || root_path)
    end
  end

  def search
    @orders = if params[:status].present? && params[:status] != 'All'
                Order.all.where(status: params[:status], restaurant_id: session[:restaurant_id])
              else
                Order.restaurant_orders(session[:restaurant_id])
              end
    authorize @orders
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def create_session
    session[:restaurant_id] ||= {} if session[:restaurant_id].nil?
  end

  def admin?
    User.find(params[:user_id]).admin?
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

# Module Helper for customers/orders
module OrdersHelper
  def find_item_name(item)
    item_type = Item.find(item)
    item_type.title
  end

  def order_present?(current_user, order)
    current_user&.admin? && order.present?
  end

  def order_admin?(current_user, order)
    current_user && order.present? && current_user.id == order.user_id
  end
end

app/views/orders/_render.html.erb
<div class= 'show'>
  <%if @orders.present? %>
    <h1>Orders</h1>
    <div class = 'item-display'>
      <% @orders.each do |order|%>
        <div class = 'orders'>
          <% if policy(order).show? %>
            <% if order_present?(current_user,order) %>
              <h2>Order No. <%= order.id %></h2>
              <h4>Status: <%= order.status%></h4>
              <%= link_to 'Show', restaurant_order_path(id: order.id, restaurant_id: order.restaurant_id) ,class: 'link'%>
            <%elsif order_admin?(current_user,order) %>
              <h2>Order No. <%= order.id %></h2>
              <h4><%= order.status%></h4>
              <%= link_to 'Show', restaurant_order_path(id: order.id, restaurant_id: order.restaurant_id), class: 'link'%>
            <% end %>
          <%end%>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/orders/index.html.erb
<div class = 'show'>
  <% unless @orders.present? %>
  <h1>No order in restaurant. </h1>
  <%end%>
  <% if @orders.present? && current_user.admin? && policy(@orders).search? %>
    <div id = 'my_select'>
      <%= form_tag(url: search_path, method: 'get', remote: true ) do%>
      <%= select_tag('Filter', options_for_select([['All',1],['ordered',2],['completed',3],['cancelled',4]])) %>
      <%end%>
    </div>
  <%end%>
  <div id= 'renderorder'>
    <%= render partial: 'render', locals: {order: @orders}%>
  </div>
</div>

app/views/orders/search.js.erb
$('#renderorder').html("<%= j (render partial: 'render') %>")

app/views/orders/show.html.erb
<div class = 'show'>
  <div class ='item-display'>
    <% if @itemorders.present? %>
      <% @itemorders.each do |itemorder|%>
        <div class = 'items1'>
          <h3>Item Title:</h3>
          <p><%= find_item_name(itemorder.item_id)%></p>
          <h4>Item Quantity:</h4>
          <p><%= itemorder.quatity%></p>
          <h4>Item Subtotal:</h4>
          <p><%= itemorder.subtotal%></p>
          <%= link_to 'Show item', restaurant_order_item_path(id: itemorder.item_id, order_id: @order.id, restaurant_id: @order.restaurant_id)%>
          <br>
        </div>
      <%end%> 
  </div>
      <% if @order.status == 'ordered' && current_user.admin? && policy(@order).update? %>
          <div class = 'plus'>
            <span><%= button_to 'Completed', { controller: 'orders', action: 'update', id: @order.id, status: 'completed' },method: :patch,
                      data:{confirm: 'Are you sure bhaijan!'}, class: 'btn btn-primary' %></span>
            <span><%= button_to 'Canceled', { controller: 'orders', action: 'update', id: @order.id, status: 'cancelled' }, method: :patch,
                      data:{confirm: 'Are you sure bhaijan!'}, class: 'btn btn-danger' %></span>
          </div>
        <%else%>
          <%user = User.find_by(id: @order.user_id)%>
          <h1> Ordered by: <%= user.full_name %></h1>
          <h3>Current Order Status: <%=@order.status%></h3>
          <h5>Created at:</h5>
          <ul> 
            <li> Date: <%=@order.created_at.strftime("%d %b. %Y")%> </li>
            <li> Time: <%=@order.created_at.strftime("%H:%M")%> </li>
          </ul>
          <h5>Updated at:</h5>
          <ul> 
            <li> Date: <%=@order.updated_at.strftime("%d %b. %Y")%> </li>
            <li> Time: <%=@order.updated_at.strftime("%H:%M")%> </li>
          </ul>
      <%end%>
    <%end%>
  <br>
</div>