config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/quantity', to: 'carts#quantity'
  get '/search', to: 'orders#search'
  post 'checkout', to: 'carts#checkout'
  post 'retire', to: 'items#retire'
  resources :carts
  resources :restaurants do
    resources :orders do
      resources :items
    end
  end
  resources :restaurants do
    resources :categories do
      resources :items
    end
  end
  root to: 'restaurants#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 10 }
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

# Home page controller
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i[destroy show]

  def index
    @restaurants = Restaurant.all
    authorize @restaurants
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    authorize @restaurant
    if @restaurant.save
      redirect_to root_path, notice: 'Restaurant Created.'
    else
      render 'new'
    end
  end

  def show
    authorize @restaurant
    if @restaurant
      # @items = @restaurant.items # n+1
      @items = Item.includes(:restaurant).where(restaurants: { id: params[:id] })
                   .paginate(page: params[:page])
    else
      flash[:alert] = @restaurant.errors.full_messages
      redirect_to(request.referer || root_path)
    end
  end

  def destroy
    authorize @restaurant
    @restaurant.destroy!
    redirect_to root_path, notice: 'Restaurant Deleted.'
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by!(id: params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

# MOdeule helper for Restaurants
module RestaurantsHelper
  def user_auth?(current_user)
    current_user.nil? || !current_user&.admin?
  end

  def popular_item?(item)
    orders = ItemOrder.all.where(item_id: item.id)
    orders.count >= 7
  end
end

app/views/restaurants/_names.html.erb
<% @restaurants.each do |rest|%>
  <h2><%= rest.name %></h2>
  <%= link_to 'Explore Restaurant' , rest, class: 'link1'%>
  <% if current_user&.admin?%>
    <%= link_to ' Delete Restaraunt', rest , method: :delete, data: {confirm: "Are you sure biro!"}, class: 'link2'%>
  <%end%>
<%end%>
<br>
<% if current_user&.admin? %>
  <%= link_to 'New restaurant', new_restaurant_path, class: 'link1'%>
<% end %>
    
    

app/views/restaurants/index.html.erb
<div class= 'home'>
  <% if current_user %>
    <% if current_user.display_name.present? %>
      <h1> <%= current_user.display_name %> </h1>
    <% else %>
      <h1> <%= current_user.email.split('@')[0] %></h1>
    <% end %>
  <% end %>
  <% if current_user&.admin? %>
    <h2> User is an admin </h2>
    <%= render partial: 'names', locals: {restaurant: @restaurants, current_user: current_user} %>
  <% elsif current_user %>
    <%= render partial: 'names', locals: {restaurant: @restaurants, current_user: current_user} %>
  <% else %>
    <%= render partial: 'names', locals: {restaurant: @restaurants, current_user: current_user} %>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class= 'show'>
  <h2>New Restaurant</h2>
  <% if @restaurant.errors.any?%>
    <%= render partial: './partial/errors', locals: {restaurant: @restaurant} %>
  <%end%>
  <%= form_for @restaurant, url: {action: 'create'}  do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br>
    <div class = 'actions'>
      <%= f.submit%>
    </div>
  <%end%>
  <%= link_to 'Back', :back, class: 'link'%>
</div>

app/views/restaurants/show.html.erb
<div class = 'show'>
  <% if !@error %>
    <h1><%=@restaurant.name%></h1>
    <% if current_user&.admin? %>
      <%= link_to 'Show user orders', restaurant_orders_path(restaurant_id: @restaurant.id, user_id: current_user.id, admin: current_user.admin), class: 'link2'%>
    <%elsif current_user %>
      <%= link_to 'Show only user orders', restaurant_orders_path(restaurant_id: @restaurant.id, user_id: current_user.id, admin: current_user.admin), class: 'link2'%>
    <%end%>
    <br>
    <%= link_to 'Categories', restaurant_categories_path(@restaurant.id), class: 'link'%>
    <% if @items.nil? ==  false %>
      <h2>Items</h2>
      <div class = 'item-display'>
        <% @items.each do |item|%>
          <%if item.available %>
            <div class = 'items1' >
              <h2>Title: <%= item.title %></h2>
              <%if popular_item?(item)%>
                <p class= 'pop'>Popular</p>
              <%end%>
              <h3>Description: </h3>
              <p><%= item.description %></p>
              <h3>Price</h3>
              <p><%= item.price %></p>
              <div class = 'img'>
                <%= image_tag(item.image) if item.image.present?%>
              </div>
              <% if policy(item).show? %>
                <% if !item_in_session?(item.title)%>
                  <%= button_to 'Add item to cart', { :controller => 'carts', :action => 'update',
                  :item_title => item.title, id: current_user.present? ? current_user.id : User.last.id + 1, :restaurant_id=> @restaurant.id,}, method: :patch, 
                  class: 'btn btn-primary' %>
                <% end %>
              <%end%>
            </div>
          <%end%>
        <%end%>
      </div>
      <%= will_paginate @items, class: 'link'%>
    <%end%>
  <%else%>
    <%= render partial: './partial/error', locals: {error: @error}%>
  <%end%>
</div>