config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/quantity', to: 'carts#quantity'
  get '/search', to: 'orders#search'
  post 'checkout', to: 'carts#checkout'
  post 'retire', to: 'items#retire'
  resources :carts
  resources :restaurants do
    resources :orders do
      resources :items
    end
  end
  resources :restaurants do
    resources :categories do
      resources :items
    end
  end
  root to: 'restaurants#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# frozen_string_literal: true

# class item model
class Item < ApplicationRecord
  self.per_page = 5

  belongs_to :restaurant
  belongs_to :cart, optional: true
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories, dependent: :destroy
  has_many :item_orders, dependent: :destroy
  has_many :orders, through: :item_orders, dependent: :destroy
  has_one_attached :image

  after_commit :add_default_cover, on: %i[create update]
  validates :title, :description, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_with CustomValidator, on: :create
  validates :title, uniqueness: { scope: :restaurant_id }

  scope :find_category_items, ->(restaurant_id) { Category.all.where(restaurant_id: restaurant_id) }

  private

  def add_default_cover
    return if image.attached?

    image.attach(io: File.open(Rails.root.join('app/assets/images/cover.jpeg')), filename: 'cover.jpeg',
                 content_type: 'image/jpeg')
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# Items Controller Action
class ItemsController < ApplicationController
  before_action :find_category, only: %i[index create]
  before_action :find_item, only: %i[edit update show destroy retire]
  before_action :find_item_category, only: %i[new create edit]

  def index
    @items = @category.items
    authorize @items
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = @category.items.new(item_params.merge(restaurant_id: params[:restaurant_id]))
    authorize @item
    if @item.save
      ItemCategory.create_item_category(@item, params[:names], params[:restaurant_id])
      redirect_to restaurant_category_items_path
    else
      render 'new'
    end
  end

  def show; end

  def edit
    authorize @item
  end

  def update
    authorize @item
    if @item.update(item_params)
      ItemCategory.create_item_category(@item, params[:names], params[:restaurant_id])
      redirect_to restaurant_category_items_path
    else
      render 'edit'
    end
  end

  def destroy
    authorize @item
    @item.destroy!
    flash[:notice] = 'Item has been deleted.'
    redirect_to restaurant_category_items_path
  end

  def retire
    authorize @item
    if @item.update(available: !@item.available)
      redirect_back(fallback_location: root_path)
      flash[:notice] = 'Item Updated.'
    else
      render 'edit'
    end
  end

  private

  def find_item
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def find_category
    @category = Category.includes(:items).find(params[:category_id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :available, :image)
  end

  def find_item_category
    @categories = Item.find_category_items(params[:restaurant_id])
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# MOdeule helper for items
module ItemsHelper
  def item_nil?(current_user, items)
    current_user&.admin? || items.nil?
  end
end

app/views/items/_form.html.erb
<%= form_for @item, url: {action: locals[:action_name] }  do |form| %>
  <% if @item.errors.any? %>
    <%= render partial: './partial/errors', locals: {restaurant: @item}%>
  <% end %>
  <div class = 'item'>
    <div class='field'>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class='field'>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class='field'>
      <%= form.label :price %>
      <%= form.text_area :price %>
    </div>

    <div class='field'>
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class='actions'>
      <%= form.submit%>
    </div>
  </div>  
  <div class = 'cat'>
    <% @categories.each do |cat| %>
      <div class = 'check'>
        <%= check_box_tag 'names[]',cat.name,(:checkb) %>
        <%= label_tag(:cat, "Add item to  #{cat.name}.") %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class='show'>
  <h1>Editing item</h1>
  <%= render 'form' , locals: {item: @item, action_name: 'update', categories: @categories } %>
</div>

app/views/items/index.html.erb
<div class= 'show'>
  <div class = 'item-display'>
    <% @items.each do |item|%>
      <div class = 'items1'>
        <%if item.available %>
          <h2>Title: <%= item.title %></h2>
          <h3>Description: </h3>
          <p><%= item.description %></p>
          <h3>Price</h3>
          <p><%= item.price %></p>
          <%if policy(item).show? %>
              <% if !item_in_session?(item.title)%>
                <%= button_to 'Add item to cart', { :controller => 'carts', :action => 'update',
                    :item_title => item.title, id: current_user.present? ? current_user.id : User.last.id + 1, :restaurant_id=> item.restaurant_id}, method: :patch,
                    class: 'btn btn-primary' %>
              <%end%>
          <%end%>
          <div class = 'img'>
                <%= image_tag(item.image) if item.image.present?%>
          </div>
        <%elsif !item.available && current_user&.admin? %>
          <h2>Title: <%= item.title %></h2>
          <h3>Description: </h3>
          <p><%= item.description %></p>
          <h3>Price</h3>
          <p><%= item.price %></p>
        <%end%>
        <% if current_user&.admin? %>
          <%= link_to 'edit item', edit_restaurant_category_item_path(id: item.id), class: 'action'%>
          <%= link_to 'Delete item', restaurant_category_item_path(id: item.id), method: :delete, data: {confirm: 'Are you sure bhaijan!'},
           class: 'action'%>
          <% if item.available%>
            <%= button_to 'Retire Item', { :controller => 'items', :action => 'retire', :id => item.id},data: {confirm: 'Are you sure bhaijan!'},
            class: 'btn btn-danger', id: 'retire' %>
          <% else %>
            <%= button_to 'Avail Item', { :controller => 'items', :action => 'retire', :id => item.id}, class: 'btn btn-danger', id: 'retire'%>
          <%end%>
        <%end%>
      </div>
    <%end%>
  </div>
  <br>
  <% if item_nil?(current_user,@items) %>
    <%= link_to 'New item', new_restaurant_category_item_path, class: 'action'%>
  <%end%>
</div>

app/views/items/new.html.erb
<div class= 'show'>
  <h1>New item</h1>
  <%= render 'form' , locals: {item: @item, action_name: 'create', categories: @categories }%>
</div>

app/views/items/show.html.erb
<div class = 'item-show'>
  <h2>Title: <%= @item.title %></h2>
  <h4> Description: </h4>
  <p><%= @item.description %></p>
  <p><b>Price:</b> <%= @item.price %></p>
  <div class = 'img1'>
    <%= image_tag(@item.image) if @item.image.present?%>
  </div>
  <%=link_to 'Back', :back, class: 'link'%>
</div>