config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/quantity', to: 'carts#quantity'
  get '/search', to: 'orders#search'
  post 'checkout', to: 'carts#checkout'
  post 'retire', to: 'items#retire'
  resources :carts
  resources :restaurants do
    resources :orders do
      resources :items
    end
  end
  resources :restaurants do
    resources :categories do
      resources :items
    end
  end
  root to: 'restaurants#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :restaurant
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 10 }
  validates :name, uniqueness: { scope: :restaurant_id }
  validates_with CustomValidator, on: :create
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# categories action controller
class CategoriesController < ApplicationController
  before_action :find_restaurant, only: %i[destroy create index]
  before_action :find_category, only: %i[destroy]

  def index
    @categories = Category.includes(:restaurant).where(restaurants: { id: params[:restaurant_id] })
    authorize @categories
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = @restaurant.categories.new(category_params)
    authorize @category
    if @category.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def destroy
    authorize @category
    @category.destroy!
    flash[:notice] = 'Category has been deleted.'
    redirect_to restaurant_categories_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.includes(:categories).find(params[:restaurant_id])
  end

  def find_category
    @category = @restaurant.categories.find(params[:id]) if @restaurant
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# MOdeule helper for categories
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class = 'show'>
  <div class= 'item-display'>
    <% @categories.each do |cat|%>
        <div class = 'items1'>
          <h2>Title: <%= cat.name %></h2>
          <%= link_to 'items' , restaurant_category_items_path(category_id: cat.id), class: 'action' %>
          <% if current_user&.admin? %>
            <%= link_to 'delete', restaurant_category_path(id: cat.id), method: :delete, data: {confirm: 'Are you sure biradar!'}, class: 'action' %>
          <% end %>
        </div>
    <%end%>
  </div>
  <br>
  <%if current_user&.admin?%>
    <%= link_to 'new', new_restaurant_category_path, class: 'action'%>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class='show'>
  <h2>New Category</h2>
  <% if @category.errors.any? %>
    <%= render partial: './partial/errors', locals: {restaurant: @category} %>
  <% end %>
  <%= form_for @category, url: {action: 'create'}  do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br>
    <div class = 'actions'>
      <%= f.submit%>
    </div>
  <%end%>
  <%= link_to 'Back', :back, class: 'link'%>
</div>